version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - efish-net
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ../cache:/data
    networks:
      - efish-net
  efish:
    volumes:
      - "${IMAGE_PATH_MOUNT}:/image"
    build:
      context: .
    restart: always
    ports: 
      - "${APP_PORT}:8080"
    stop_grace_period: 0s
    networks:
      - efish-net

networks:
    efish-net:
        driver: bridge

volumes:
  db:
    driver: local
